"""live表增加了url字段

Revision ID: f7e3222411b8
Revises: be5f2b1b9b1c
Create Date: 2018-05-03 16:22:06.086520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e3222411b8'
down_revision = 'be5f2b1b9b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live', sa.Column('url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live', 'url')
    # ### end Alembic commands ###
